name: Build & Release MATEKF405SE

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build MATEKF405SE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Cache toolchain
        uses: actions/cache@v4
        id: cache-toolchain
        with:
          path: tools
          key: ${{ runner.os }}-${{ hashFiles('mk/tools.mk') }}

      - name: Install toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make arm_sdk_install

      - name: Install picotool
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make picotool_install

      - name: Hydrate configuration
        run: make configs
        
      - name: Setup environment
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "OPT_FLAGS=-O3" >> $GITHUB_ENV
          else
            echo "OPT_FLAGS=-Og" >> $GITHUB_ENV
          fi

      - name: Build MATEKF405SE
        run: make EXTRA_FLAGS=-Werror MATEKF405SE

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MATEKF405SE
          path: obj/*.hex

  release:
    name: Upload to Release
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        
      - name: Verify HEX
        run: ls -al 
        
      - name: Upload HEX to Release
        run: |
          TAG="${GITHUB_REF##*/}"
          gh release upload "$TAG" *.hex --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
