name: Build MATEKF405SE

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build F405SE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Cache build toolchain
        uses: actions/cache@v4
        id: cache-toolchain
        with:
          path: tools
          key: ${{ runner.os }}-${{ hashFiles('mk/tools.mk') }}

      - name: Install toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make arm_sdk_install

      - name: Install picotool
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: make picotool_install

      - name: Hydrate configuration
        run: make configs

      - name: Build target MATEKF405SE
        run: make EXTRA_FLAGS=-Werror MATEKF405SE_rev

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MATEKF405SE
          path: obj/*.hex

  release:
    name: Attach HEX to Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v5

      - name: List files
        run: ls -R .

      - name: Attach HEX to Release
        run: |
          TAG="${GITHUB_REF##*/}"
          gh release upload "$TAG" MATEKF405SE/*.hex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
